#!/bin/sh
# ----------------------------------------------------------------------
# ПОЛНАЯ ПЕРЕУСТАНОВКА И НАСТРОЙКА ZEROTIER НА OPENWRT 23.05+ (APK)
# ----------------------------------------------------------------------
# Адаптировано для OpenWrt с пакетным менеджером APK
# ----------------------------------------------------------------------

# ЦВЕТА ДЛЯ ВЫВОДА
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo "${YELLOW}=================================================================${NC}"
echo "${YELLOW}    ПОЛНАЯ ПЕРЕУСТАНОВКА И НАСТРОЙКА ZEROTIER ДЛЯ OPENWRT 23.5+${NC}"
echo "${YELLOW}              (Пакетный менеджер APK)${NC}"
echo "${YELLOW}=================================================================${NC}"

# ----------------------------------------------------------------------
# ШАГ 1: ID СЕТИ (❕ ИЗМЕНИТЕ НА СВОЙ)
# ----------------------------------------------------------------------
NETWORK_ID="cf719fd540faee8e"
echo "${YELLOW}Будет использована сеть: ${NETWORK_ID}${NC}"

# ----------------------------------------------------------------------
# ШАГ 2: ОСТАНОВКА И ПОЛНОЕ УДАЛЕНИЕ СТАРЫХ КОНФИГУРАЦИЙ
# ----------------------------------------------------------------------
echo "${YELLOW}[1/9] Остановка ZeroTier и удаление старых конфигураций...${NC}"

# Остановить сервис
/etc/init.d/zerotier stop 2>/dev/null
killall zerotier-one 2>/dev/null
sleep 2

# Удалить все следы ZeroTier
rm -rf /var/lib/zerotier-one/*
rm -rf /etc/zerotier/*
rm -f /etc/config/zerotier
rm -f /tmp/.uci/zerotier
uci revert zerotier 2>/dev/null

echo "${GREEN}✓ Старые конфигурации удалены${NC}"

# ----------------------------------------------------------------------
# ШАГ 3: ОБНОВЛЕНИЕ СПИСКА ПАКЕТОВ (APK)
# ----------------------------------------------------------------------
echo "${YELLOW}[2/9] Обновление списка пакетов (apk update)...${NC}"
apk update

if [ $? -ne 0 ]; then
    echo "${RED}✗ Ошибка при обновлении списка пакетов${NC}"
    exit 1
fi
echo "${GREEN}✓ Список пакетов обновлен${NC}"

# ----------------------------------------------------------------------
# ШАГ 4: УДАЛЕНИЕ СТАРОЙ ВЕРСИИ (ЕСЛИ УСТАНОВЛЕНА)
# ----------------------------------------------------------------------
echo "${YELLOW}[3/9] Проверка и удаление старой версии ZeroTier...${NC}"

if apk info | grep -q zerotier; then
    echo "Найдена установленная версия ZeroTier. Удаляю..."
    apk del zerotier
    if [ $? -eq 0 ]; then
        echo "${GREEN}✓ Старая версия удалена${NC}"
    else
        echo "${YELLOW}⚠ Проблема при удалении, продолжаем...${NC}"
    fi
else
    echo "ZeroTier не установлен или уже удален"
fi

# ----------------------------------------------------------------------
# ШАГ 5: УСТАНОВКА ZEROTIER (APK)
# ----------------------------------------------------------------------
echo "${YELLOW}[4/9] Установка ZeroTier (apk add zerotier)...${NC}"
apk add zerotier

if [ $? -ne 0 ]; then
    echo "${RED}✗ Ошибка установки ZeroTier${NC}"
    exit 1
fi
echo "${GREEN}✓ ZeroTier успешно установлен${NC}"

# ----------------------------------------------------------------------
# ШАГ 6: СОЗДАНИЕ КОНФИГУРАЦИОННОГО ФАЙЛА
# ----------------------------------------------------------------------
echo "${YELLOW}[5/9] Создание конфигурационного файла...${NC}"

cat > /etc/config/zerotier << EOF
# ZeroTier configuration for OpenWrt 23.05+ (APK)
# Generated by setup script

config zerotier 'global'
	option enabled '1'
	option port '9993'
	# Секрет будет сгенерирован автоматически при первом запуске
	option secret ''

# Подключение к сети - используем список join
config zerotier 'main_network'
	option enabled '1'
	list join '${NETWORK_ID}'
EOF

echo "Конфигурация создана:"
cat /etc/config/zerotier
echo "${GREEN}✓ Конфигурационный файл создан${NC}"

# ----------------------------------------------------------------------
# ШАГ 7: ВКЛЮЧЕНИЕ АВТОЗАПУСКА
# ----------------------------------------------------------------------
echo "${YELLOW}[6/9] Включение автозапуска...${NC}"
/etc/init.d/zerotier enable
echo "${GREEN}✓ Автозапуск включен${NC}"

# ----------------------------------------------------------------------
# ШАГ 8: ЗАПУСК ZEROTIER
# ----------------------------------------------------------------------
echo "${YELLOW}[7/9] Запуск ZeroTier...${NC}"
/etc/init.d/zerotier start

# Ждем инициализации
echo "Ожидание инициализации (20 секунд)..."
sleep 20

# ----------------------------------------------------------------------
# ШАГ 9: ПРОВЕРКА СТАТУСА
# ----------------------------------------------------------------------
echo "${YELLOW}[8/9] Проверка статуса ZeroTier...${NC}"

# Проверить статус
STATUS=$(zerotier-cli status 2>/dev/null)
echo "Статус: $STATUS"

if echo "$STATUS" | grep -q "ONLINE"; then
    echo "${GREEN}✓ ZeroTier работает в режиме ONLINE${NC}"
else
    echo "${YELLOW}⚠ ZeroTier ещё в режиме OFFLINE. Даём ещё 10 секунд...${NC}"
    sleep 10
    zerotier-cli status
fi

# ----------------------------------------------------------------------
# ШАГ 10: ПРОВЕРКА ПОДКЛЮЧЕННЫХ СЕТЕЙ
# ----------------------------------------------------------------------
echo "${YELLOW}[9/9] Проверка подключенных сетей...${NC}"
zerotier-cli listnetworks

# ----------------------------------------------------------------------
# ШАГ 11: НАСТРОЙКА ФАЙРВОЛА
# ----------------------------------------------------------------------
echo "${YELLOW}[Доп. 1/3] Настройка файрвола для доступа к LAN...${NC}"

# Получаем имя интерфейса ZeroTier
ZT_DEV=$(ip link show | grep -o 'zt[^:]*' | head -1)

if [ -n "$ZT_DEV" ]; then
    echo "Найден интерфейс ZeroTier: $ZT_DEV"
    
    # Создаем интерфейс в сети OpenWrt
    uci set network.zerotier=interface
    uci set network.zerotier.proto='none'
    uci set network.zerotier.device="$ZT_DEV"
    
    # Создаем зону файрвола для VPN
    uci add firewall zone
    uci set firewall.@zone[-1].name='vpn'
    uci set firewall.@zone[-1].input='ACCEPT'
    uci set firewall.@zone[-1].output='ACCEPT'
    uci set firewall.@zone[-1].forward='ACCEPT'
    uci set firewall.@zone[-1].masq='1'
    uci add_list firewall.@zone[-1].network='zerotier'
    
    # Создаем правила форвардинга между зонами
    uci add firewall forwarding
    uci set firewall.@forwarding[-1].src='vpn'
    uci set firewall.@forwarding[-1].dest='lan'
    
    uci add firewall forwarding
    uci set firewall.@forwarding[-1].src='vpn'
    uci set firewall.@forwarding[-1].dest='wan'
    
    uci add firewall forwarding
    uci set firewall.@forwarding[-1].src='lan'
    uci set firewall.@forwarding[-1].dest='vpn'
    
    # Применяем изменения
    uci commit network
    uci commit firewall
    
    echo "${GREEN}✓ Файрвол (зоны) настроен${NC}"
    
    # ----------------------------------------------------------------------
    # ШАГ 12: ОТКРЫТИЕ ПОРТА 9993
    # ----------------------------------------------------------------------
    echo "${YELLOW}[Доп. 2/3] Открываем порт 9993 UDP для входящих соединений...${NC}"
    
    # Проверяем, есть ли уже такое правило
    if ! uci show firewall | grep -q "Allow-ZeroTier-Inbound"; then
        uci add firewall rule
        uci set firewall.@rule[-1].name='Allow-ZeroTier-Inbound'
        uci set firewall.@rule[-1].src='*'
        uci set firewall.@rule[-1].target='ACCEPT'
        uci set firewall.@rule[-1].proto='udp'
        uci set firewall.@rule[-1].dest_port='9993'
        uci commit firewall
        echo "${GREEN}✓ Порт 9993 открыт${NC}"
    else
        echo "Правило для порта 9993 уже существует"
    fi
    
    # Перезапускаем firewall
    /etc/init.d/firewall restart
    echo "${GREEN}✓ Firewall перезапущен${NC}"
    
else
    echo "${YELLOW}⚠ Интерфейс ZeroTier пока не создан"
    echo "  Вы можете настроить файрвол позже командой: /etc/init.d/firewall restart${NC}"
fi

# ----------------------------------------------------------------------
# ШАГ 13: СОХРАНЕНИЕ СЕКРЕТНОГО КЛЮЧА
# ----------------------------------------------------------------------
echo "${YELLOW}[Доп. 3/3] Сохранение секретного ключа...${NC}"

# Подождем немного, чтобы секрет сгенерировался
sleep 5

if [ -f /var/lib/zerotier-one/identity.secret ]; then
    SECRET=$(cat /var/lib/zerotier-one/identity.secret)
    # Добавляем секрет в конфиг, чтобы он сохранялся после перезагрузок 
    uci set zerotier.global.secret="$SECRET"
    uci commit zerotier
    echo "${GREEN}✓ Секретный ключ сохранён в конфигурации${NC}"
else
    echo "${YELLOW}⚠ Файл с секретом пока не создан${NC}"
fi

# ----------------------------------------------------------------------
# ШАГ 14: ПРОВЕРКА УСТАНОВЛЕННЫХ ПАКЕТОВ (ДЛЯ ИНФОРМАЦИИ)
# ----------------------------------------------------------------------
echo "${YELLOW}[Инфо] Установленные пакеты ZeroTier:${NC}"
apk info | grep zerotier

# ----------------------------------------------------------------------
# ФИНАЛЬНЫЙ ОТЧЁТ
# ----------------------------------------------------------------------
echo "${GREEN}=================================================================${NC}"
echo "${GREEN}    НАСТРОЙКА ЗАВЕРШЕНА${NC}"
echo "${GREEN}=================================================================${NC}"
echo ""
echo "${YELLOW}ТЕКУЩИЙ СТАТУС:${NC}"
zerotier-cli status
echo ""
echo "${YELLOW}ПОДКЛЮЧЕННЫЕ СЕТИ:${NC}"
zerotier-cli listnetworks
echo ""
echo "${YELLOW}ЧТО ДЕЛАТЬ ДАЛЬШЕ:${NC}"
echo "1. Зайдите на https://my.zerotier.com"
echo "2. Найдите сеть с ID: ${NETWORK_ID}"
echo "3. Авторизуйте устройство с MAC: $(zerotier-cli listnetworks 2>/dev/null | grep -Eo '([0-9a-f]{2}:){5}[0-9a-f]{2}' | head -1)"
echo "4. После авторизации IP появится в списке сетей"
echo ""
echo "${YELLOW}ПОЛЕЗНЫЕ КОМАНДЫ:${NC}"
echo "  zerotier-cli status                    # статус сервиса"
echo "  zerotier-cli listnetworks               # список сетей и IP"
echo "  zerotier-cli join ${NETWORK_ID}         # подключиться к сети"
echo "  zerotier-cli leave ${NETWORK_ID}        # отключиться от сети"
echo "  /etc/init.d/zerotier restart            # перезапустить сервис"
echo "  apk info | grep zerotier                # информация о пакете"
echo ""
echo "${GREEN}ГОТОВО!${NC}"
